services:
  thermia-back:
    build:
      context: ./thermia-back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - thermia-back/.env
    restart: unless-stopped

  thermia-front:
    build:
      context: ./thermia-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - thermia-back
    env_file:
      - thermia-back/.env
    restart: unless-stopped
