[pytest]
filterwarnings =
    ignore::cryptography.utils.CryptographyDeprecationWarning
    ignore::DeprecationWarning:paramiko
    ignore::UserWarning:langchain_core
    ignore::DeprecationWarning:slowapi
