#!/usr/bin/env python3
"""factory_knowledge_dashboard.py — Cross-project lesson dashboard generator.

Reads a JSONL of engram observations (export of `aidlc/_shared/*` topic keys)
and renders a markdown rollup with provenance — used by humans browsing the
shared corpus and by future onboarding to surface learned-once-applied-everywhere
patterns.

Input format (one object per line):
    {"sync_id", "project": "_shared", "kind", "title", "body",
     "tags": [...], "topic_key": "aidlc/_shared/<kind>/<slug>",
     "provenance": [{"sync_id": ..., "project": ..., "title": ...}, ...]}

Output (markdown):
    aidlc-docs/knowledge/cross-project.md

Usage:
    python3 aidlc-scripts/factory_knowledge_dashboard.py \\
        --observations shared.jsonl \\
        --out aidlc-docs/knowledge/cross-project.md

Exit codes:
    0  dashboard generated
    1  no shared observations found
    2  usage error
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import defaultdict
from pathlib import Path

ORCHESTRATOR_VERSION = "0.2.0"


def _die(msg: str, code: int = 2) -> None:
    print(f"factory_knowledge_dashboard: error: {msg}", file=sys.stderr)
    sys.exit(code)


def _load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        _die(f"observations file not found: {path}")
    out: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError as exc:
            _die(f"invalid JSON: {exc}")
    return out


def _is_shared(obs: dict) -> bool:
    tk = obs.get("topic_key") or ""
    return tk.startswith("aidlc/_shared/") or obs.get("project") == "_shared"


def render(observations: list[dict]) -> str:
    shared = [o for o in observations if _is_shared(o)]
    today = dt.date.today().isoformat()

    if not shared:
        return f"# Cross-Project Knowledge — {today}\n\n_No shared observations yet._\n"

    by_kind: dict[str, list[dict]] = defaultdict(list)
    for o in shared:
        by_kind[o.get("kind", "uncategorized")].append(o)

    total_projects = set()
    for o in shared:
        for p in o.get("provenance") or []:
            if isinstance(p, dict) and "project" in p:
                total_projects.add(p["project"])

    lines = [
        f"# Cross-Project Knowledge — {today}",
        "",
        f"Shared observations: **{len(shared)}** across {len(by_kind)} kind(s), "
        f"sourced from {len(total_projects)} project(s).",
        "",
        "*Generated by `aidlc-scripts/factory_knowledge_dashboard.py`. Each "
        "observation lists its project provenance so unpromotion is reversible.*",
        "",
    ]

    for kind in sorted(by_kind):
        items = sorted(by_kind[kind], key=lambda o: o.get("title", ""))
        lines.append(f"## {kind.title()} ({len(items)})\n")
        for o in items:
            title = o.get("title") or "(untitled)"
            tk = o.get("topic_key") or "(no topic key)"
            sync = o.get("sync_id", "")
            provenance = o.get("provenance") or []
            tags = o.get("tags") or []

            lines.append(f"### {title}")
            lines.append("")
            lines.append(f"- **topic_key**: `{tk}`")
            if sync:
                lines.append(f"- **sync_id**: `{sync}`")
            if tags:
                lines.append(f"- **tags**: {', '.join('`' + t + '`' for t in tags)}")
            if provenance:
                provs = sorted(set(p.get("project", "?") for p in provenance if isinstance(p, dict)))
                lines.append(f"- **promoted from**: {', '.join(provs)}")
                lines.append(f"- **source sync_ids**: " +
                             ", ".join(f"`{p.get('sync_id','?')}`"
                                       for p in provenance if isinstance(p, dict)))
            body = (o.get("body") or "").strip()
            if body:
                # Indent the body as a block so headers in body don't escape this section
                lines.append("")
                for bl in body.splitlines():
                    lines.append(f"> {bl}")
            lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(prog="factory_knowledge_dashboard.py")
    parser.add_argument("--observations", required=True,
                        help="JSONL export of engram observations")
    parser.add_argument("--out", default=None,
                        help="Output markdown file (default: aidlc-docs/knowledge/cross-project.md)")
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--allow-empty", action="store_true",
                        help="exit 0 even when no shared observations found")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve() if args.repo_root \
        else Path(__file__).resolve().parent.parent

    obs = _load_jsonl(Path(args.observations).resolve())
    markdown = render(obs)

    has_shared = any(_is_shared(o) for o in obs)

    out_path = Path(args.out).resolve() if args.out \
        else repo_root / "aidlc-docs" / "knowledge" / "cross-project.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown + ("\n" if not markdown.endswith("\n") else ""),
                        encoding="utf-8")

    print(f"factory_knowledge_dashboard: wrote {out_path}",
          file=sys.stderr)

    if not has_shared and not args.allow_empty:
        sys.exit(1)


if __name__ == "__main__":
    main()
