"""
SQLAlchemy ORM models for Thermia.
No database connection is required to import this module.
"""
from sqlalchemy import Column, Index, Text, func
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, VARCHAR
from sqlalchemy.orm import declarative_base
from sqlalchemy.types import Uuid

from pgvector.sqlalchemy import Vector

Base = declarative_base()


class Document(Base):
    """
    Represents a document stored in the `documents` table.

    Columns
    -------
    id               : UUID primary key, generated by PostgreSQL gen_random_uuid()
    content          : Full text of the document (NOT NULL)
    embedding        : 1024-dimensional vector embedding (pgvector)
    tsvector         : Pre-computed tsvector for full-text search
    metadata_        : Arbitrary JSON metadata (maps to column name `metadata`)
    status           : Document status label (e.g. "vigente", "derogada") — VARCHAR(32)
    legal_rank       : Legal rank / hierarchy (e.g. "ley", "decreto") — VARCHAR(64)
    jurisdiction     : Jurisdiction ISO-like code (e.g. "ES", "EU") — VARCHAR(8)
    source_metadata_ : Raw provider metadata payload (maps to column `source_metadata`)
    """

    __tablename__ = "documents"

    __table_args__ = (
        # ivfflat ANN index — lists=50 tuned for 10k–50k chunks
        Index(
            "idx_documents_embedding",
            "embedding",
            postgresql_using="ivfflat",
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"lists": 50},
        ),
        # GIN full-text search index
        Index("idx_documents_tsvector", "tsvector", postgresql_using="gin"),
        # B-tree indexes for legal-filter equality / IN queries
        Index("ix_documents_status", "status"),
        Index("ix_documents_legal_rank", "legal_rank"),
        Index("ix_documents_jurisdiction", "jurisdiction"),
        # GIN index on curated metadata for @> containment queries
        Index(
            "ix_documents_metadata_gin",
            "metadata",
            postgresql_using="gin",
            postgresql_ops={"metadata": "jsonb_path_ops"},
        ),
    )

    id = Column(
        Uuid(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    content = Column(Text, nullable=False)
    embedding = Column(Vector(1024))
    tsvector = Column(TSVECTOR)
    metadata_ = Column("metadata", JSONB, server_default="{}")
    status = Column(VARCHAR(32), nullable=True, default="")
    legal_rank = Column(VARCHAR(64), nullable=True, default="")
    jurisdiction = Column(VARCHAR(8), nullable=True, default="")
    source_metadata_ = Column("source_metadata", JSONB, nullable=True)
