"""
SQLAlchemy ORM models for Thermia.
No database connection is required to import this module.
"""
from sqlalchemy import Column, Text, func
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import declarative_base
from sqlalchemy.types import Uuid

from pgvector.sqlalchemy import Vector

Base = declarative_base()


class Document(Base):
    """
    Represents a document stored in the `documents` table.

    Columns
    -------
    id          : UUID primary key, generated by PostgreSQL gen_random_uuid()
    content     : Full text of the document (NOT NULL)
    embedding   : 1024-dimensional vector embedding (pgvector)
    tsvector    : Pre-computed tsvector for full-text search
    metadata_   : Arbitrary JSON metadata (maps to column name `metadata`)
    """

    __tablename__ = "documents"

    id = Column(
        Uuid(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    content = Column(Text, nullable=False)
    embedding = Column(Vector(1024))
    tsvector = Column(TSVECTOR)
    metadata_ = Column("metadata", JSONB, server_default="{}")
